spring.application.name=CityBlockMap


#H2{
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.datasource.username=user
spring.datasource.password=12345

spring.h2.console.path=/h2
spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true
spring.jpa.defer-datasource-initialization=true

################################################
#   IMPORTANTE-PARA-EXECUTAR-NO-WSL            #
#   http://172.x.x.x:8080/h2                   #
#   Driver Class   = org.h2.Driver             #
#   JDBC           = jdbc:h2:mem:testdb        #
#   username       = user                      #
#   password       = 12345                     #
################################################
#}

server.address=0.0.0.0