spring.application.name=CityBlockMap

spring.profiles.active=test
spring.jpa.open-in-view=true

#H2{


################################################
#   IMPORTANTE-PARA-EXECUTAR-NO-WSL            #
#   http://172.x.x.x:8080/h2                   #
#   Driver Class   = org.h2.Driver             #
#   JDBC           = jdbc:h2:mem:testdb        #
#   username       = user                      #
#   password       = 12345                     #
################################################
#}

server.address=0.0.0.0